### ISSUE TITLE
VTubeStudioError: Unknown messageType: EventSubscriptionRequest

### ISSUE THREAD

**Issue by Ben-Lillie** [Hawkbat/VTubeStudioJS#10]
When trying to subscribe to any event the follow error is thrown

VTubeStudioError: Unknown messageType: EventSubscriptionRequest (Error Code: 7 RequestTypeUnknown) 

NodeJS 16.10.0
Package Version: 3.1.0

**Comment by Hawkbat** [comment]
It's likely you're using a version of VTube Studio that doesn't have the event system API. Are you using the Steam beta version of VTube Studio?

**Comment by Ben-Lillie** [comment]
Not using the beta version and yes launching from steam.

![siooA5x](https://user-images.githubusercontent.com/9092504/187545533-294313cf-8a2a-40be-8cde-a9864f03ff7e.png)

**Comment by Hawkbat** [comment]
That's likely the issue then. Events are currently only available in the beta version of VTube Studio, as they're still being tested. They should work with the normal version of VTube Studio after the next major release.

**Comment by Ben-Lillie** [comment]
Ah there we go working now, thanks for you help, I probably should've checked the VTube Studio discord first
