### ISSUE TITLE
Request: Add a method to permanently close the connection

### ISSUE THREAD

**Issue by adarah** [Hawkbat/VTubeStudioJS#12]
Hi again! In the plugin I'm working on, I'd like to be able to close the connection to VTS until the user chooses to re-enable it. I could be mistaken but I didn't find any methods to close the connection other than [this one](https://github.com/Hawkbat/VTubeStudioJS/blob/224619fdb84fb8b911b4224ebdab1f412385eb52/src/endpoints.ts#L780), but it's private and it tries to reconnect after a short while. Would you be ok with me opening a PR to add a "disconnect"/"quit" method? It would basically do the same as `_disconnect` but  without the auto-reconnect mechanism

**Comment by Hawkbat** [comment]
Sounds reasonable to me. Go for it!
