### ISSUE TITLE
Support ItemPinRequest

### ISSUE THREAD

**Issue by adarah** [Hawkbat/VTubeStudioJS#17]
Hi, I think a new API endpoint `ItemPinRequest` was added 4 months ago. Do you plan to support it?

**Comment by Hawkbat** [comment]
Thanks for bringing it to my attention! I don't actively use VTube Studio so I haven't been keeping up with updates to the API as closely. I'll find some time to update VTubeStudioJS to support the latest API version 👍

**Comment by Hawkbat** [comment]
All missing requests and events have been added in the newly published v3.4.0! Let me know if you encounter any issues.
