### ISSUE TITLE
[Feature Request] Include "file" property for hotkeys

### ISSUE THREAD

**Issue by eslym** [Hawkbat/VTubeStudioJS#2]
I realize the hotkey only include the `id`, `name` and `type`, the `file` property is missing
it could be useful when someone doesn't name their hotkeys

**Comment by Hawkbat** [comment]
Good catch, I must've missed that when I updated the raw API calls. Just pushed out version `1.1.0` to npm that adds that `file` property to the hotkey's OOP wrapper class.

**Comment by eslym** [comment]
wow so fast 😂

**Comment by Hawkbat** [comment]
Was in the middle of looking into your other issue actually, and it was a small change to fix ^_^
